import { rollup1, rollup2,rollup3,bill1,bill2,bill3,book1,book2,book3,broc1,broc2,broc3,card1,card2,card3,disp1,disp2,disp3,event1,event2,event3,fabric1,fabric2,fabric3,grap1,grap2,grap3,floor2,floor3,lamp1,lamp2,annual1,annual2,annual3,show1,show2,show3 } from './Images'
import { products } from '../../../constants/NavabrData'
import { device1, device2,device3,device4,device5,device6 } from '.'

export const galleryImages = [
    {
        category:products[0].title,
        image:rollup1
    },
    {
        category:products[0].title,
        image:rollup2
    },
    {
        category:products[0].title,
        image:rollup3
    },
    {
        category:products[1].title,
        image:grap1
    },
    {
        category:products[1].title,
        image:grap2
    },
    {
        category:products[1].title,
        image:grap3
    },
    {
        category:products[2].title,
        image:annual1
    },
    {
        category:products[2].title,
        image:annual2
    },
    {
        category:products[2].title,
        image:annual3
    },
    {
        category:products[3].title,
        image:book1
    },
    {
        category:products[3].title,
        image:book2
    },
    {
        category:products[3].title,
        image:book3
    },
    {
        category:products[4].title,
        image:broc1
    },
    {
        category:products[4].title,
        image:broc2
    },
    {
        category:products[4].title,
        image:broc3
    },
    {
        category:products[5].title,
        image:card1
    },
    {
        category:products[5].title,
        image:card2
    },
    {
        category:products[5].title,
        image:card3
    },
    {
        category:products[6].title,
        image:fabric1
    },
    {
        category:products[6].title,
        image:fabric2
    },
    {
        category:products[6].title,
        image:fabric3
    },
    {
        category:products[7].title,
        image:floor2
    },
    {
        category:products[7].title,
        image:floor3
    },
    {
        category:products[8].title,
        image:lamp1
    },
    {
        category:products[8].title,
        image:lamp2
    },
    {
        category:products[9].title,
        image:event1
    },
    {
        category:products[9].title,
        image:event2
    },
    {
        category:products[9].title,
        image:event3
    },
    {
        category:products[10].title,
        image:disp1
    },
    {
        category:products[10].title,
        image:disp2
    },
    {
        category:products[10].title,
        image:disp3
    },
    {
        category:products[11].title,
        image:show1
    },
    {
        category:products[11].title,
        image:show2
    },
    {
        category:products[11].title,
        image:show3
    },
    {
        category:products[12].title,
        image:bill1
    },
    {
        category:products[12].title,
        image:bill2
    },
    {
        category:products[12].title,
        image:bill3
    }
]

export const deviceData = [
    {
        name:'device1',
        image:device1
    },
    {
        name:'device2',
        image:device2
    },
    {
        name:'device3',
        image:device3
    },
    {
        name:'device4',
        image:device4
    },
    {
        name:'device5',
        image:device5
    },
    {
        name:'device6',
        image:device6
    },
]