export { default as digital } from './large digital printing.png'
export { default as digital1 } from './digital1.png.jpg'
export { default as offset1 } from './offset1.png'
export { default as offset2 } from './offset2.png'
export { default as offset3 } from './offset3.png'

export { default as digitalPrinting } from './digital.png'
export { default as cont1 } from './cont1.png'
export { default as cont2 } from './cont2.png'

export { default as whatsapp } from './whatsapp.png'
export { default as logo } from './logo.png'
export { default as logo1 } from './logo1.png'

export { default as banner1 } from './Banner1.bmp'
export { default as banner2 } from './Banner 2.jpg'
export { default as banner3 } from './Banner 3.jpg'
export { default as banner4 } from './Banner 4.jpg'
export{ default as banner } from './banner last.png'
export { default as contact } from './contact.png'