export { default as Box } from './Box Package.png'
export { default as Business } from './Business Card blue.png'
export { default as Elegant } from './Elegant Business Card.png'
export { default as Holiday } from './Holiday Postcard.png'
export { default as Invitation } from './Invitation Card Yellow.png'
export { default as Square } from './Square Box.png'
export { default as Carry } from './Carry Bag.png'
export { default as Corporate } from './Corporate trifold Brochure.png'
export { default as banner } from './banner mid.png'
export { default as picks} from './picks.png'
export { default  as mug } from './Mug.png'
export { default as Sticker } from './Sticker.png'
export { default as Sweatshirt } from './Sweatshirt.png'
export { default as Mouse } from './Mouse Pad.png'
export { default as Badge } from './Badge.png'
export { default as Case } from './Phone Case.png'
export { default as hot } from './hot deal.png'
export { default as newArrival } from './new.png'
export { default as banner2 } from './banner 2.png'

export { default as Badge1 } from './Badge1.png';
export { default as Master } from './Business Card Master.png'
export {  default as Cap } from './Cap.png'
export { default as Catalogue } from './Catalogue Green.png'
export { default as Caremic } from './Ceremic Mug Cup.png'
export { default as Package } from './Corporate trifold Package.png'
export { default as Creative } from './Creative Life.png'
export { default as Flyer } from './Flyer.png'
export { default as Return } from './Return of Book.png'

export { default as digital } from './large digital printing.png'
export { default as digital1 } from './digital1.png.jpg'
export { default as offset1 } from './offset1.png'
export { default as offset2 } from './offset2.png'
export { default as offset3 } from './offset3.png'

export { default as digitalPrinting } from './digital.png'
export { default as cont1 } from './cont1.png'
export { default as cont2 } from './cont2.png'

export { default as whatsapp } from './whatsapp.png'

export { default as bgImage } from './bg-image.png';